### ISSUE TITLE
sysctl::default should be in run_list when using resource[sysctl_param]

### ISSUE THREAD

**Issue by vills** [sous-chefs/sysctl#19]
In #9 you asked about cases, where I don't care about persist sysctl params. So, what about nodes without persistent store? For example, nodes with boot over PXE.

Also, i wanna use only resource, but i should add sysctl::default in run list, or use include_recipe.

Maybe resource should invoke recipe[default] by itself in a code?

**Comment by donaldguy** [comment]
With no persistent disk store I see 4 scenarios (well technically 8, but the first below covers 5 combinations):

1. only chef run on boot OR NO persistent chef server & NO transient file store (e.g. ramdisk)
The cookbook isn't really gonna gain you anything; the resource is literally just gonna run `sysctl -w key=value` (before failing at the template); you may as well save on the bandwidth syncing the cookbook and just write the `execute` resources into your recipe

2. regular runs during uptime; YES persistent chef server / NO transient disk
Your best bet here is to set `normal` attributes in the `[:sysctl][:param]` space and using `sysctl::apply`; things will work idempotently

3. regular runs during uptime; NO persistent chef server YES transient disk
you can use my branch in #20 with the resources and include_recipe `sysctl` or put it in your run list; this will give you mutable idempotence for the life of your nodes

4. regular runs during uptime; YES persistent chef server YES transient disk
Decide between 2 and 3 depending on whether there is an idea of persistent identity of a logical node between incarnations or not; if yes, 2 - if not, 3.

Scenarion 3 (i.e. #20 ) could be made useful for persistent logical nodes if it were modified slightly to check in the provider merely against `node['sysctl']['params]` rather than `node.default['sysctl']['params]` specifically; I am not sure for the original reasoning behind the specificity but I didn't feel empowered to / have a need to change it

**Comment by svanzoest** [comment]
Thanks for the feedback guys! It helps to get other perspectives on this. Sometimes you get too stuck in the weeds.

**Comment by jaymzh** [comment]
Not sure what you're asking. At Facebook we run Chef every 15 minutes and we enforce all sysctls are converged. Unlike most of our cookbooks, we actually go through the extra effort of inspecting any sysctls we care about, not just notifying on `/etc/sysctl.conf` changes (we did this largely because we found software that liked to manually twiddle sysctls). Looking at the original bug reference, this is precisely why we push a model where never managing individual elements of a thing (like a single sysctl, or a single cron entry) and always manage a whole service (all sysctls, all crons). It's the only way to gaurantee that when someone nukes the recipe code that's defining a cron/sysctl/whatever that it ACTUALLY goes away, because we detect a change in /etc/sysctl.conf and tell the subsystem to reload all of them. We try never to do things like call `cron` or `sysctl`, but only to write a file and have the system reconfigure itself.

As to the lack of persistence... who cares if it's a pxe-booted system? There's no harm in writing out a file if it's truly ephemeral. On the other hand, if it's say an embedded system where the root FS is not a real FS, it's nice to have Chef write out to some persistent place that boot scripts can look at so you don't come up poorly tuned waiting for your first Chef run.

**Comment by svanzoest** [comment]
Thanks @jaymzh you answered perfectly.

**Comment by axelrtgs** [comment]
Was just following up on issues and PRs and giving some attention to the sysctl cookbook and was wondering if this was still relevant since its over 2 years old or if its been addressed sometime in between and the issue is just lingering.
