### ISSUE TITLE
Config managed by attribute won't restart procps if value is modified with sysctl -w manually 

### ISSUE THREAD

**Issue by karthik-altiscale** [sous-chefs/sysctl#88]
### Cookbook version
latest

### Chef-client version
12.5+

### Platform Details
centos

### Scenario:
say I have node['sysctl']['params']['vm']['swappiness'] = 20
and someone on the host changes it `sysctl -w vm.swappiness=19` (but sysctl.conf and 99-chef-attributes.conf) is not altered
in case of lwrp sysctl_param 'vm.swappines' it works fine because it runs `systl -w` everytime [https://github.com/sous-chefs/sysctl/blob/master/providers/param.rb#L22](here)

### Steps to Reproduce:
see above

### Expected Result:
sysctl value should be set to what is mentioned in node attribute

### Actual Result:
nothing happens, just skips thinking its already upto date.

**Comment by vchung-nz** [comment]
I think you have to use sysctl_param resource to enforce your defined values against runtime changes.  Values set as attributes are managed like a chef templates, so a reload is only triggered when the file been changed.

**Comment by axelrtgs** [comment]
Have you included the sysctl::apply recipe somewhere in your run list or by include as suggested in the readme [https://github.com/sous-chefs/sysctl#setting-sysctl-parameters]

From what i understand the reload only happens when something changes or when a reboot happens.

@vchung-nz is correct int he functioning and using the parameters aproach will only reload when the template file changes since it uses notifications to process the reload.

the resource would be your best option to solve this otherwise you can write out some logic checking if the value is different and then reloading or just reloading on every chef run but IMHO its probably much easier to use the resources.

is there a specific use case where using the resources is unfeasible vs the params?

**Comment by damacus** [comment]
I'm going to close this now due to lack of response. 

Please reopen if you're still having trouble with this!
